# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbf743d9053e4e58c85e80d61c34c6e1f20b8d17b00f1376ea4639a26e6f945e42116d4af733c32f1decf5f1171bc2d1bfd95348dfcdfae4bcc1fa38bd80cd5

test:
  secret_key_base: 30dddc34c203720f809c1fe31646c0fee95820197482819ea3289090d174ca92bbff3e0abd849c604f2802d5f9e9b59c1f88e69900ed453920948529ed6b8136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
